version: '3'
services:
  isi_datamart:
    network_mode: "host"
    build: .
    depends_on:
      - memcached
      - blazegraph_satellite
      - redis
      - datamart_wikifier
    ports:
      - "9000:9000"
    volumes:
      - .:/app/datamart-upload
      - ../datamart-userend:/app/datamart-userend
      - /nfs1/dsbox-repo/data/datasets-v32/seed_datasets_data_augmentation:/data
      - /data/datamart-system/data/memcache_storage:/root/memcache_storage
  datamart_wikifier:
    network_mode: "host"
    image: "datamart-wikifier:latest"
  memcached:
    network_mode: "host"
    image: "memcached:alpine"
    command: ["memcached", "-p", "11211", "-u", "nobody", "-c", "1024", "-m", "1024", "-I", "100m"]
  blazegraph_satellite:
    network_mode: "host"
    image: lyrasis/blazegraph:2.1.5
    environment:
      - BLAZEGRAPH_UID=$ISI_BLAZEGRAPH_UID
      - BLAZEGRAPH_GID=$ISI_BLAZEGRAPH_GID
    ports:
      - 9002:8080
    volumes:
      - ./config/blazegraph/RWStore.properties:/RWStore.properties
      - $ISI_BLAZEGRAPH_SATELLITE_DATA_DIR:/data
  redis:
    # image: "redis:alpine"
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile-redis
    command: ["redis-server", "/conf/redis_conf.conf"]
    expose:
      - 6379
    volumes:
      - $ISI_REDIS_DATA_DIR:/data
      - $ISI_REDIS_CONF_DIR:/conf
