site_name: Datamart Schemas
nav:
  - Dataset Metadata Schema: index.md
  - Data Schema: download.md
  - APIs: api.md
  - API Tutorial: REST-API-tutorial.md
theme: 
  name: material
  logo: 'logo.png'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
