site_name: Datamart Schemas
nav:
  - Dataset Schema: index.md
  - Data Download Schema: download.md
theme: 
  name: material
  logo: 'logo.png'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
