swagger: '2.0'
info:
  version: 1.0.0
  title: Datamart Link Panel
basePath: /
paths:
  /search:
    post:
      tags:
        - Search API
      summary: Search
      description: '<p>The main search function for isi datamart, should always call this api first. Currently supplied_data is necessary. Currently query do not make influence on isi datamart search. <br> <br> One parameters are required: <br> 1. "data":It could be a csv file, or a path to a csv file or a d3m dataset id(for example: "DA_poverty_estimation") The option for uploading the path or dataset id is not shown here. <br> Two parameters are optional: 1. "max_return_docs": A int indicate how many results want to get returned from search, if not given, the default value will be 20. <br> 2. "query": a json-like query used to add more searching rquirements. </p>'
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: query
          in: formData
          type: string
          required: false
          description: The query
        - name: data
          in: formData
          type: file
          required: true
          description: '<p>Supplied data file, you can try to upload a exmaple file from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/test_search_data.csv">here</a>.</p>'
        - name: max_return_docs
          in: query
          type: integer
          required: false
          description: Max return docs (default 20 if not given)
          example: 20
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/SearchResult'
        '404':
          description: Not found.
  /download:
    post:
      tags:
        - Download API
      summary: Download
      description: '<p>The function used to download the searched result with given search result adapted from search API. It will only return the portions of the dataset referenced by id that matches well with data. If no rows can be joined, an error will be raised. <br><br> Three parameters are required: <br> 1 ."task": The string format search result(adapted from search api). <br> 2."data": The supplied data (a csv file or a path to the csv file). <br>  3. "format": Return format(general csv format or d3m format with metadata).</p>'
      consumes:
        - multipart/form-data
      produces:
        - application/zip
      parameters:
        - name: task
          in: formData
          type: string
          required: true
          description: '<p>The search result task (json-like str) from search api you can try to copy the content from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_search_result_wikidata.txt">example1</a> or <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_search_result_general.txt">example2</a> </p>'
        - name: data
          in: formData
          type: file
          required: true
          description: '<p>Supplied data file, you can try to upload a exmaple file from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/test_search_data.csv">here</a>.</p>'
        - name: format
          in: formData
          type: string
          enum:
            - csv
            - d3m
          required: true
          description: Download format(general csv format or d3m format)
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: file
        '404':
          description: Not found.
  /download/{id}:
    get:
      tags:
        - Download API
      summary: Download the dataset with given id
      description: '<p>The function used to download the dataset with the supplied datamart id. Different from download, it will return the whole dataset without join hint column. <br> If a wikidata format id is given, it will return maximum 100 random Q nodes with those properties. <br> <br>Two parameters are required: <br> 1. "id": The datamart id, can be found from search result. <br> 2. "format": Return format(general csv format or d3m format with metadata).</p>'
      consumes:
        - multipart/form-data
      produces:
        - application/zip
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: ID of datamart
          example: 'D1000001'
        - name: format
          in: query
          type: string
          enum:
            - csv
            - d3m
          required: true
          description: Download format
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: file
        '404':
          description: Not found.
  /augment:
    post:
      tags:
        - Augment API
      summary: Augment dataset
      description: '<p>The function used to download the searched result with given search result adapted from search API. It will only return the portions of the dataset referenced by id that matches well with data. If no rows can be joined, an error will be raised.<br> <br> Three parameters are required: <br> 1 ."task": The string format search result as "task"(adapted from search api). <br> 2."data": The supplied data (a csv file or a path to the csv file). <br>  3. "format": Return format(general csv format or d3m format with metadata). <br> Two parameters are optional: <br> 4. "destination": If given, the system will save the augmented dataset to the path and return the path. If not given, it will return the results to user as download function. <br> 5."columns": used to control which column number required to append on the supplied data. If not given, all columns will be appened. </p>'
      consumes:
        - multipart/form-data
      produces:
        - application/zip
      parameters:
        - name: task
          in: formData
          type: string
          required: true
          description: '<p>The search result task (json-like str) from search api you can try to copy the content from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_search_result_wikidata.txt">example1</a> or <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_search_result_general.txt">example2</a> </p>'
        - name: data
          in: formData
          type: file
          required: true
          description: '<p>Supplied data file, you can try to upload a exmaple file from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/test_search_data.csv">here</a>.</p>'
        - name: format
          in: formData
          type: string
          enum:
            - csv
            - d3m
          required: true
          description: Download format
        - name: columns
          in: formData
          type: string
          required: false
          description: Optional parameter, a str indicate the list of column indices from the Datamart dataset that should be appened. See format example below, If not given, all possible columns from search results will be appended.
          example: '1, 3'
        - name: destination
          in: formData
          type: string
          required: false
          description: If given, the augmented results(in csv or d3m) will be saved to the given path. If not given, the augmented result will be returned to the user for download. See the example for the destination format
          example: /Users/claire/Desktop
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: file
        '404':
          description: Not found.
  /upload/generateWD+Metadata:
    post:
      tags:
        - Upload API
      summary: upload the url of input file
      description: '<p>The first part of upload, the function used to materilize the given url and generate the corresponding metadata that will be stored in to datamart database. User can check and edit if they want. It will return two list, first list is a list of the materilized csv results, the second list is a list of json file which indicates the WD+ metadata.<br><br> Two parameters are required: 1. "url": The link to the target file. <br> 2. "file_type": A string indicate which type of the uploaded object is, currently only online_csv is available.</p> '
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: url
          in: query
          type: string
          required: true
          description: Url of input file
          example: 'https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/test_upload_data.csv'
        - name: file_type
          in: query
          type: string
          enum:
            - online_csv
          required: true
          description: Online file type, currently only support online_csv
      responses:
        '200':
          description: 'successful operation'
          schema:
            $ref: '#/definitions/ProcessResult'
        '404':
          description: Not found.
  /upload/uploadWD+Metadata:
    post:
      tags:
        - Upload API
      summary: upload data and metadata
      description: '<p>Second part of upload, the function used the genrated data and metadata from "/generateWD+Metadata" and upload to datamart database.<br><br> Two parameters are required: 1. "data_input": A list of the csv data generated from step 1. <br> 2. "file_type": A list of the database metadata for isi datamart generated from step 2.</p>'
      consumes:
        - multipart/form-data
      produces:
        - application/text
      parameters:
        - name: data_input
          in: formData
          type: string
          required: true
          description: '<p>Data(in list format) from load_and_process api, you can try to copy the content from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_upload_part1_data.txt">here</a> </p>'
        - name: metadata
          in: formData
          type: string
          required: true
          description: '<p>Metadata(in list format) from load_and_process api, you can try to copy the content from <a href="https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/sample_upload_part1_metadata.txt">here</a> </p>'
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: file
        '404':
          description: Not found.
  /upload:
    post:
      tags:
        - Upload API
      summary: upload data and metadata
      description: '<p>ALL-IN-ONE upload method that take a url indicate the file path and the file type. The function will automatically generate the metadata and upload to datamart database. It is RECOMMEND to use this function to upload the dataset instead of the 2-step one. <br> <br> Two parameters are required: 1. "url": The link to the target file. <br> 2. "file_type": A string indicate which type of the uploaded object is, currently only online_csv is available. </p>'
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: url
          in: query
          type: string
          required: true
          description: Url of input file
          example: 'https://raw.githubusercontent.com/usc-isi-i2/datamart-upload/d3m/datamart_web/test_upload_data.csv'
        - name: file_type
          in: query
          type: string
          enum:
            - online_csv
          required: true
          description: Online file type, currently only support online_csv
      responses:
        '200':
          description: 'successful operation'
          schema:
            $ref: '#/definitions/ProcessResult'
        '404':
          description: Not found.
definitions:
  SearchResult:
    type: object
    properties:
      summary:
        type: string
      datamart_id:
        type: string
      score:
        type: number
      materialize_info:
        type: object
        properties:
          id:
            type: string
          score:
            type: number
          metadata:
            type: object
            properties:
              connection_url:
                type: string
              search_result:
                type: object
                properties:
                  p_nodes_needed:
                    type: array
                    items:
                      type: string
                  target_q_node_column_name:
                    type: string
              query_json:
                type: string
              search_type:
                type: string
          augmentation:
            type: object
            properties:
              properties:
                type: string
              left_columns:
                type: array
                items:
                  type: integer
              right_columns:
                type: array
                items:
                  type: integer
              datamart_type:
                type: string
      metadata:
        type: array
        items:
          type: object
          properties:
            selector:
              type: array
              items:
                type: string
            metadata:
              type: object
              properties:
                structural_type:
                  type: string
                semantic_types:
                  type: array
                  items:
                    type: string
                dimension:
                  type: object
                  properties:
                    name:
                      type: string
                    semantic_types:
                      type: array
                      items:
                        type: string
                    length:
                      type: integer
                schema:
                  type: string
  ProcessResult:
    type: object
    properties:
      data:
        type: array
        items:
          type: string
      metadata:
        type: array
        items:
          type: object
          properties:
            datamart_id:
              type: string
            materialization:
              type: object
              properties:
                python_path:
                  type: string
                arguments:
                  type: object
                  properties:
                    url:
                      type: string
                    file_type:
                      type: string
            variables:
              type: array
              items:
                type: object
                properties:
                  datamart_id:
                    type: string
                  semantic_type:
                    type: array
                    items:
                      type: string
                  name:
                    type: string
                  description:
                    type: string
                  named_entity:
                    type: array
                    items:
                      type: string
                  temporal_coverage:
                    type: object
                    properties:
                      start:
                        type: string
                      end:
                        type: string
            title:
              type: string
            description:
              type: string
            keywords:
              type: array
              items:
                type: string
            url:
              type: string
            file_type:
              type: string
            xpath:
              type: string
tags:
  - name: Search API
  - name: Download API
  - name: Augment API
  - name: Upload API
#  Datamart:
#    type: object
#    properties:
#      File Name:
#        type: string
#      Datamart ID:
#        type: string
#      Score:
#        type: number
#      Description:
#        type: string
#      URL:
#        type: string
#      Columns:
#        type: array
#        items:
#          type: string
#      Recommend Join Columns:
#        type: string